### ISSUE TITLE
How to programmaticaly filter a collection

### ISSUE THREAD

**Issue by MadeByKarl** [direct-fuel-injection/bbGrid#75]
Hi, I want to programmatically filter the collection once it's fetched. So I do it in onReady but since you must trigger a change event, it calls onReady and so on.

How can I achieve this?

Thanks.

**Comment by direct-fuel-injection** [comment]
Hello, write collection.comparator - it will automatically sort your collection before ready

**Comment by MadeByKarl** [comment]
Thanks! I'll look into that :).

*Karl Delandsheere*
*freelance photographer, web designer*

skype:*karl.delandsheere • *Liège, *Belgium*

*madebykarl.be <http://madebykarl.be/>* ~ web & print communication
*hobography.net <http://hobography.net/>* • *@hobography_net
<https://twitter.com/hobography_net>* ~ travel & photography blog
*yummy-planet.com <http://yummy-planet.com/>* • *@YummyPlanetBlog
<https://twitter.com/YummyPlanetBlog>* ~ food & travel blog
karl.delandsheere.be ~ more about me and what I do

2015-09-14 8:26 GMT+02:00 Алексей <notifications@github.com>:
